### ISSUE TITLE
Implement cmd click (open tab in background)

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#325]
I just noticed that CMD click does not always open a new tab, for example it does not seems to work on wiki link on the right of this page. Not sure why, maybe because image is used in the link instead of text ?

**Comment by paulrouget** [comment]
Bug + patch: https://bugzilla.mozilla.org/show_bug.cgi?id=1156615

**Comment by paulrouget** [comment]
Fixed in graphene-40.0a1.en-US.mac64.dmg.

**Comment by gordonbrander** [comment]
We ran into this again here: https://github.com/mozilla/browser.html/pull/597#issuecomment-130948480

**Comment by Gozala** [comment]
It looks like some links still do not work (see https://github.com/mozilla/browser.html/pull/597#issuecomment-130948480) apparently happens on http://www.theverge.com
I tried to debug and it seems that event is not fired so it must be on graphene side.

**Comment by paulrouget** [comment]
Any link in particular?

**Comment by gordonbrander** [comment]
@paulrouget for me, all links on http://theverge.com/ home page did not work

**Comment by Gozala** [comment]
Our target runtime is on Servo so no point in keeping gecko issues open.

**Comment by gordonbrander** [comment]
I'm pretty sure this is not a Gecko issue, but a JS issue. Our current front-end no longer opens any links in background on command click. We should implement this. Renaming bug.

**Comment by paulrouget** [comment]
This will also require servo support.

**Comment by paulrouget** [comment]
I'll file a new issue (this bug was mostly about gecko implementation).

**Comment by paulrouget** [comment]
servo: https://github.com/servo/servo/issues/10099
bhtml: https://github.com/browserhtml/browserhtml/issues/940
